--SolvedByOracle

-- 문제1
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID
-- 문제2
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;
-- 문제3
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'Sick' ORDER BY ANIMAL_ID
-- 문제4
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION <> 'Aged' ORDER BY ANIMAL_ID
-- 문제5
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID
-- 문제6
SELECT ANIMAL_ID , NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC
-- 문제7
SELECT NAME FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) WHERE ROWNUM <= 1
